services:
  db:
    image: postgres:latest
    container_name: keystore-postgres
    environment:
      POSTGRES_USER: root-test
      POSTGRES_PASSWORD: root-test
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: keystore-rabbit
    environment:
      RABBITMQ_DEFAULT_USER: root-test
      RABBITMQ_DEFAULT_PASS: root-test
    ports:
      - "5672:5672"
      - "15672:15672"

  seq:
    image: datalust/seq
    container_name: keystore-seq
    environment:
      - ACCEPT_EULA=Y
      - SEQ_USER=${SEQ_USER}
      - SEQ_PASSWORD=${SEQ_PASSWORD}
    ports:
      - "5341:80"
volumes:
  db_data: