// <auto-generated />
using System;
using Keystore.Infrastructure.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Keystore.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(KeystoreDbContext))]
    partial class KeystoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Keystore.Domain.Aggregates.KeyBundle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccessKey")
                        .HasColumnType("uuid")
                        .HasColumnName("access_key");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<DateTime?>("Deleted")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted");

                    b.Property<byte[]>("IdentityKey")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("identity_key");

                    b.Property<int>("RegistrationId")
                        .HasColumnType("integer")
                        .HasColumnName("registration_id");

                    b.Property<byte[]>("SignedPreKeyPublic")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("signed_pre_key_public");

                    b.Property<byte[]>("SignedPreKeySignature")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("signed_pre_key_signature");

                    b.Property<DateTime>("SignedPreKeyTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("signed_pre_key_timestamp");

                    b.Property<int>("SignedPrekeyId")
                        .HasColumnType("integer")
                        .HasColumnName("signed_pre_key_id");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated");

                    b.HasKey("Id");

                    b.HasIndex("AccessKey")
                        .IsUnique()
                        .HasDatabaseName("idx_access_key");

                    b.ToTable("key_bundle", (string)null);
                });

            modelBuilder.Entity("Keystore.Domain.Entities.PreKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Consumed")
                        .HasColumnType("boolean")
                        .HasColumnName("consumed");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<DateTime?>("Deleted")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted");

                    b.Property<Guid>("KeyBundleId")
                        .HasColumnType("uuid")
                        .HasColumnName("key_bundle_id");

                    b.Property<int>("KeyId")
                        .HasColumnType("integer")
                        .HasColumnName("key_id");

                    b.Property<byte[]>("PublicKey")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("public_key");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated");

                    b.HasKey("Id");

                    b.HasIndex("KeyBundleId");

                    b.ToTable("pre_key", (string)null);
                });

            modelBuilder.Entity("Keystore.Infrastructure.Persistence.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime>("OccurredOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on");

                    b.Property<DateTime?>("ProcessedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("outbox_message", (string)null);
                });

            modelBuilder.Entity("Keystore.Domain.Entities.PreKey", b =>
                {
                    b.HasOne("Keystore.Domain.Aggregates.KeyBundle", "KeyBundle")
                        .WithMany("PreKeys")
                        .HasForeignKey("KeyBundleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KeyBundle");
                });

            modelBuilder.Entity("Keystore.Domain.Aggregates.KeyBundle", b =>
                {
                    b.Navigation("PreKeys");
                });
#pragma warning restore 612, 618
        }
    }
}
