name: Build & Test (.NET 9 preview)

on:
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
          quality: preview

      - name: nuget.config token
        run: |
          sed -i "s|%NUGET_TOKEN%|${{ secrets.GH_PACKAGES_TOKEN }}|g" nuget.config

      - run: dotnet restore
      - run: dotnet build --no-restore
      - run: dotnet test --no-build --verbosity normal
