name: Build & Test (.NET 9 preview)

on:
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
          quality: preview

      - name: Add GitHub NuGet source
        run: dotnet nuget add source "https://nuget.pkg.github.com/KristianJBorgwarth/index.json" --name "github" --username ${{ github.actor }} --password ${{ secrets.NUGET_TOKEN }} --store-password-in-clear-text

      - run: dotnet restore
      - run: dotnet build --no-restore
      - run: dotnet test --no-build --verbosity normal
